---
title: "Homework 2"
output: github_document
---
```{r}
library(tidyverse)
```

```{r}
data <- read_tsv("../data/tables/example_dataset_2.tsv") %>%
  print()
```

```{r}
data <- data %>%
mutate(mean_ratio = mean_yfp / mean_rfp) %>%
print()
```

```{r}
data %>%
mutate(mean_ratio = round(mean_ratio, 2)) %>%
print()
```

```{r}
annotations <- read_tsv("../data/tables/example_dataset_3.tsv") %>%
print()
```

```{r}
data %>%
inner_join(annotations, by = "strain") %>%
print()
```

```{r}
data %>%
left_join(annotations, by = "strain") %>%
print()
```

```{r}
data %>%
right_join(annotations, by = "strain") %>%
print()
```

```{r}
data %>%
summarize(max_yfp = max(mean_yfp),
max_rfp = max(mean_rfp)) %>%
print()
```

```{r}
data <- read_tsv("../data/tables/example_dataset_4.tsv") %>%
print(n = 10)
```

```{r}
data %>%
group_by(strain) %>%
print(n = 10)
```

```{r}
data %>%
group_by(strain) %>%
summarize(mean_yfp = mean(yfp), mean_rfp = mean(rfp)) %>%
print()
```

```{r}
data %>%
group_by(strain) %>%
summarize(mean_yfp = mean(yfp), mean_rfp = mean(rfp),
se_yfp = sd(yfp) / sqrt(n()),
se_rfp = sd(rfp) / sqrt(n())) %>%
print()
```

```{r}
data %>%
group_by(strain) %>%
summarize(mean_yfp = mean(yfp), mean_rfp = mean(rfp)) %>%
mutate(mean_ratio = mean_yfp / mean_rfp) %>%
left_join(annotations, by = "strain") %>%
print()
```

```{r}
data %>%
group_by(strain) %>%
summarize(mean_yfp = mean(yfp), mean_rfp = mean(rfp)) %>%
mutate(mean_ratio = mean_yfp / mean_rfp) %>%
left_join(annotations, by = "strain") %>%
ggplot(aes(x = kozak_region, y = mean_ratio,
color = insert_sequence, group = insert_sequence)) +
geom_line() +
geom_point()
```
